description: LightGBM
exp_name: the-competition-name
run_name: run000
fe_name: ""
cols_definition:
  id_col: id
  target_col: y
  categorical_col: [
    hoge,
    fuga,
  ]
  cv_group: Municipality
model_name: ModelLGBM
kfold:
  method: stratified_group
  number: 5
seed: 42
params: {
    objective: regression,
    metric: rmse,
    num_leaves: 63,
    max_depth: 5,
    feature_fraction: 0.8,
    subsample_freq: 1,
    bagging_fraction: 0.7,
    min_data_in_leaf: 10,
    learning_rate: 0.1,
    boosting: gbdt,
    lambda_l1: 0.4,
    lambda_l2: 0.4,
    verbosity: -1,
    random_state: 42,
    num_boost_round: 5000,
    early_stopping_rounds: 100,
}
evaluation_metric: rmsle
